Updated travis configuration

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -66,10 +66,14 @@ script:
   # - php $CLI_HOME/typo3/cli_dispatch.phpsh phpunit typo3conf/ext/$REPO/Tests/Unit
   - >
     if [ -d "TYPO3.CMS" ]; then
+      echo "Go to TYPO3.CMS";
       cd TYPO3.CMS/;
-    fi;
-    if [ -d "../TYPO3.CMS" ]; then
+    elif [ -d "../TYPO3.CMS" ]; then
+      echo "Go to ../TYPO3.CMS";
       cd ../TYPO3.CMS/;
+    else
+      echo "TYPO3.CMS folder not found";
+      exit 1;
     fi;
 
     export typo3DatabaseName="typo3";
@@ -77,13 +81,18 @@ script:
     export typo3DatabaseUsername="root";
     export typo3DatabasePassword="";
 
+    echo ""
+    echo ""
+    echo "ls ./";
     ls -hal ./;
+
+    echo ""
+    echo ""
+    echo "make and link ext dir";
 
     mkdir -p ./typo3conf/ext/;
     ln -s $CLI_HOME ./typo3conf/ext/$REPO;
-
     ls -hal ./typo3conf/ext/;
 
-
     find ./typo3conf/ext/rest/Tests/Functional -path '*Test.php' -print;
-    find ./typo3conf/ext/rest/Tests/Functional -path '*Test.php' -exec ./bin/phpunit --colors -c typo3/sysext/core/Build/FunctionalTests.xml {} \; ;
+    find ./typo3conf/ext/rest/Tests/Functional -path '*Test.php' -exec phpunit --colors -c typo3/sysext/core/Build/FunctionalTests.xml {} \; ;
